name = input("Enter your name:")
branch = input("Enter your branch:")
year = int(input("Enter your year of study:"))
college = input("Enter your college name:")
cgpa = float(input("Enter your CGPA:"))
print("Student Details:")
print("Name:", name)
print("Branch:", branch)
print("Year of Study:", year)
print("College:", college)
print("CGPA:", cgpa)